### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by Prog19** [Bridgei2i/JiraTimeTracker#1]
I understand this project was developed as an alternative to adding on a paid plugin for the generation of time sheet. I would like to suggest a non-automated yet easy way to export JIRA issues to csv.  
`On your JIRA Dashboard, Choose Issues -> Search for issues -> Apply filters of your choice -> Export -> Excel(All fields) -> Convert .xls to .csv`

**Comment by shark8me** [comment]
:)

That's a much simpler solution, thanks for pointing it out.

A little bit of context here. Initially, there were 2 time trackers used at Bridgei2i, Jira and ApolloHQ. Since more people used ApolloHQ, those who used JIRA has to make time tracking entries twice. This tool was meant to programmatically extract that info from Jira and publish it to ApolloHQ (via their API). 

This project never got that far (w.r.t. the publish to ApolloHQ part). However, we decided to open source it in case someone else finds it useful (perhaps to push the data into a different system).

thanks!
